### ISSUE TITLE
Naming of perstister

### ISSUE THREAD

**Issue by jantoebes** [scalapenos/stamina#13]
I think the name persister is not correct. Is has nothing to do with persisting. Persisting is the part which akka-persistence does.

In fact it is a migrator. If you call it migrator you can read the code much more naturally:

``` scala
val v2CartCreatedMigrator = migrator[CartCreatedV2, V2]("cart-created",
  from[V1].to[V2](_.update('cart / 'items / * / 'price ! set[Int](1000)))
)
```

Next to it 'persisted' is also not a good name. But in my opinion it is the context you need for the decoding the bytes. I can only think of horrible other names like CodecInfo or CodecContext, but i hope you get my point.

**Comment by agemooij** [comment]
The problem here i that the best name, i.e. "serializer" has already been taken by Akka and reusing it would be very confusing. A Persister can be "direct", i.e. a V1 persister, in which case the term "migrator"  doesn't make any sense. I think of it as a serializer with migration support, hence the fact that the terms "Migrator" and "Migration" already exist in stamina-json and that they will very probably move into stamina-core. Codec/Encoding was also already taken for the actual binary envelope stuff.

This leaves a naming void and both "persister" and the result of running a persister, i.e. "persisted" made the most sense since this library is very much concerned with persisted and unpersisting data in the context of akka-persistence.

Good, solid, well-fitting suggestions for better names will be looked upon with an open and curious mind ;)
