### ISSUE TITLE
scala 2.13

### ISSUE THREAD

**Issue by larochef** [scalapenos/stamina#74]
I've been using stamina in the real world, and I must thank you for it.

I'm currently upgrading my application to scala 2.13 and stamina is one of the last missing ones.

Are you planning to make a 2.13 release soon? Since the project seems dead, I'd understand that I'd have to handle it myself.

**Comment by agemooij** [comment]
Hi @larochef . The project is indeed relatively dead, mostly because the main authors (that would be mostly me and @raboof) have not needed to use it the last few years. AFAIK there is still a need for a solution like this, even though akka has added some minor improvements over the years.

If you are an active user and you would like to upgrade and release it for 2.13, then I'm happy to make you a full team member.

**Comment by larochef** [comment]
Hi @agemooij, and thx for quick answer.

Making the code compatible with 2.13 shouldn't be that hard, the issue will rather be pushing it to maven central. 

I've been using stamina for about 2 years, and have been able to handle evolutions in events required by the business changes in the application. I'd love to see a more efficient way to store the data and also more choice in the json providers, but I doubt I'll find time soon to work on it.

**Comment by agemooij** [comment]
Let me know how I can help. If you want to update the build to support 2.13 then I can review, merge, and release.

**Comment by larochef** [comment]
souds fair.

I hope I can get it ready soon enough.

**Comment by larochef** [comment]
I created #75 
@agemooij tell me if you see anything wou'd like me to change.

**Comment by larochef** [comment]
@agemooij there's been a review on the PR, can you see for the next step?
